services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper 

  mongodb:
    image: mongo:latest
    ports:
    - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: lenga
      MONGO_INITDB_ROOT_PASSWORD: password

  LogisticsSys:
    build:
      context: ./LogisticsSystem
      dockerfile: DockerFile
    depends_on:
      - kafka
      - mongodb
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - KAFKA_URL=kafka:29092

  StandardSys:
    build:
      context: ./StandardSystem
      dockerfile: Dockerfile
    depends_on:
      - kafka
    environment:
      - KAFKA_URL=kafka:29092

  ExpressSys:
    build:
      context: ./ExpressSystem
      dockerfile: Dockerfile
    depends_on:
      - kafka
    environment:
      - KAFKA_URL=kafka:29092

  InternationalSys:
    build:
      context: ./InternationalSystem
      dockerfile: Dockerfile
    depends_on:
      - kafka
    environment:
      - KAFKA_URL=kafka:29092

  Client:
    build:
      context: ./Client
      dockerfile: Dockerfile
    depends_on:
      - kafka
    environment:
      - KAFKA_URL=kafka:29092
